debug: true

server:
  port: 8080
  servlet:
    context-path: /api

springfox:
  documentation:
    swagger-ui:
      base-url: /
    swagger:
      v2:
        enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migrate
    table: zz_flyway_migration
    baseline-on-migrate: true
  application:
    admin:
      enabled:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
